CREATE TABLE PRODUCTS(
ID NUMBER,
CONSTRAINT PRODUCT_ID PRIMARY KEY (ID),
NAME NVARCHAR2(50),
MANUFACTURER_NAME NVARCHAR2(50),
COST_PRICE NUMBER
);

--lesson3
INSERT INTO PRODUCTS
VALUES(1001, 'toy123', 'someManufacturer', 10);

INSERT INTO PRODUCTS
VALUES(1002, 't-shirt', 'MANUFACTURE', 20);

INSERT INTO PRODUCTS
VALUES(1003, 'toy123', 'MANUFACTURE', 30);

INSERT INTO PRODUCTS
VALUES(1004, 'TEST1', 'MANUFACTURE', 40);

INSERT INTO PRODUCTS
VALUES(1005, 'toy123', 'MANUFACTURE', 50);

INSERT INTO PRODUCTS
VALUES(1006, 'toy123', 'MANUFACTURE', 60);

INSERT INTO PRODUCTS
VALUES(1007, 't-shirt', 'MANUFACTURE', 70);

INSERT INTO PRODUCTS
VALUES(1008, 'toy123', 'MANUFACTURE', 80);

INSERT INTO PRODUCTS
VALUES(1009, 'TEST1', 'someManufacturer', 90);

INSERT INTO PRODUCTS
VALUES(1010, 't-shirt', 'MANUFACTURE', 100);

INSERT INTO PRODUCTS
VALUES(1060, 'TEST1', 'MANUFACTURE', 100);

--ВЫБОРКА ПРОДУКТОВ COST_PRICE = 50 AND NAME = 'toy123'
SELECT * FROM PRODUCTS WHERE COST_PRICE = 50 AND NAME = 'toy123';
--ВЫБОРКА ПРОДУКТОВ ID = 1005 OR COST_PRICE < 50
SELECT * FROM PRODUCTS WHERE ID = 1005 OR COST_PRICE < 50;
--ВЫБОРКА ПРОДУКТОВ ID > 1005 AND MANUFACTURER - SOME_MANUFACTURER
SELECT * FROM PRODUCTS WHERE ID > 1005 AND MANUFACTURER_NAME = 'someManufacturer';
--ВЫБОРКА ВСЕХ ПРОДУКТОВ
SELECT * FROM PRODUCTS;

--update products where name = t-shirt. New value to MANUFACTURER_NAME = china
UPDATE PRODUCTS SET MANUFACTURER_NAME = 'china' WHERE NAME = 't-shirt';

--delete products where id < 1050
DELETE FROM PRODUCTS WHERE ID < 1050;